version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: stripe-example
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    ports:
      - '5431:5432'
# web:
#   image: stripe-example-multi-stage
#   depends_on:
#     - db
#   ports:
#     - '4000:4000'
